[package]
name = "start-sessionrunner"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "^1", features = ["macros", "rt-multi-thread", "sync", "signal", "process", "io-util"] }
sessionrunner = { path = "../sessionrunner" }
