name: Release

on:
  push:
    tags:        
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust nightly
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
        source $HOME/.cargo/env
    - name: Install pam-sys Dependencies
      run: sudo apt-get install -y libpam0g-dev
    - name: Build
      run: cargo build --verbose

  archlinux_build:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:latest
      volumes:
        - /usr:/usr-host
        - /opt:/opt-host
      options: --privileged
    steps:
    - name: Maximize build space
      run: |
        df -h
        rm -rf /usr-host/share/dotnet
        rm -rf /usr-host/share/swift
        rm -rf /usr-host/share/java
        rm -rf /usr-host/local/lib/android
        rm -rf /opt-host/ghc
        rm -rf /opt-host/hostedtoolcache
        rm -rf /opt-host/az
        df -h
    - uses: actions/checkout@v4
    - name: Update system
      run: pacman -Syu --noconfirm
    - name: Install Basic Software
      run: pacman -S --noconfirm sudo curl
    - name: Install Build Dependencies
      run: pacman -S --noconfirm base-devel
    - name: Install rustup
      run: pacman -S --noconfirm rustup
    - name: Set default rust toolchain
      run: rustup default stable
    - name: Compile software
      run: make all
    - name: Create package
      run: |
        mkdir prefix
        make PREFIX=prefix install
        cd prefix && tar -cjf ../login_ng.tar.bz2 . && cd ..
    - name: Move build artifact
      run: |
        for file in *.tar.bz2; do mv "$file" "${file%.tar.bz2}.bin.tar.bz2"; done
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: archlinux-package
        path: |
          *.tar.bz2
        if-no-files-found: error

  bitbake_build:
    runs-on: ubuntu-latest
    container: 
      image: debian:bookworm
      volumes:
        - /usr:/usr-host
        - /opt:/opt-host
      options: --privileged
    steps:
    - name: Maximize build space
      run: |
        df -h
        rm -rf /usr-host/share/dotnet
        rm -rf /usr-host/share/swift
        rm -rf /usr-host/share/java
        rm -rf /usr-host/local/lib/android
        rm -rf /opt-host/ghc
        rm -rf /opt-host/hostedtoolcache
        rm -rf /opt-host/az
        df -h
    - uses: actions/checkout@v4
    - name: Update system
      run: |
        apt-get update -y
        apt-get upgrade -y
    - name: Install Basic Software
      run: apt-get install -y sudo curl
    - name: Install Build Dependencies
      run: apt-get install -y build-essential devscripts debhelper pkg-config libpam0g-dev libssl-dev cargo zip
    - name: Install cargo-bitbake
      run: |
        cargo install cargo-bitbake --locked
        find / -name "cargo-bitbake"
    - name: Build bitbake
      run: |
        mkdir ../bitbake
        cd sessionrunner
        cargo build
        /github/home/.cargo/bin/cargo-bitbake bitbake
        mv *.bb ../bitbake
        cd ..
        cd sessionexec
        cargo build
        /github/home/.cargo/bin/cargo-bitbake bitbake
        mv *.bb ../bitbake
        cd ..
    - name: Build bitbake
      run: zip -r bitbake.zip bitbake
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: bitbake-package
        path: |
          *.zip
        if-no-files-found: error

  bookworm_build:
    runs-on: ubuntu-latest
    container: 
      image: debian:bookworm
      volumes:
        - /usr:/usr-host
        - /opt:/opt-host
      options: --privileged
    steps:
    - name: Maximize build space
      run: |
        df -h
        rm -rf /usr-host/share/dotnet
        rm -rf /usr-host/share/swift
        rm -rf /usr-host/share/java
        rm -rf /usr-host/local/lib/android
        rm -rf /opt-host/ghc
        rm -rf /opt-host/hostedtoolcache
        rm -rf /opt-host/az
        df -h
    - uses: actions/checkout@v4
    - name: Update system
      run: |
        apt-get update -y
        apt-get upgrade -y
    - name: Install Basic Software
      run: apt-get install -y sudo curl
    - name: Install Build Dependencies
      run: apt-get install -y build-essential devscripts debhelper
    - name: Install pam-sys Dependencies
      run: apt-get install -y libpam0g-dev
    - name: Install Rust toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain stable -y
    - name: Build deb
      run: |
        . $HOME/.cargo/env
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo install cargo-deb
        make deb
    - name: Move debs
      run: |
        mv target/debian/*.deb .
        for file in *.deb; do mv "$file" "${file%.deb}.bookworm.deb"; done
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: bookworm-package
        path: |
          *.deb
        if-no-files-found: error

  sources_collect:
    runs-on: ubuntu-latest
    container: 
      image: archlinux:latest
      volumes:
        - /usr:/usr-host
        - /opt:/opt-host
      options: --privileged
    steps:
    - name: Maximize build space
      run: |
        df -h
        rm -rf /usr-host/share/dotnet
        rm -rf /usr-host/share/swift
        rm -rf /usr-host/share/java
        rm -rf /usr-host/local/lib/android
        rm -rf /opt-host/ghc
        rm -rf /opt-host/hostedtoolcache
        rm -rf /opt-host/az
        df -h
    - uses: actions/checkout@v4
    - name: Update system
      run: pacman -Syu --noconfirm
    - name: Install Basic Software
      run: pacman -S --noconfirm tar bzip2
    - name: Collect sources
      run: |
        tar -cjf ../login_ng.src.tar.bz2 .
        mv ../login_ng.src.tar.bz2 .
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: sources-package
        path: |
          *.tar.bz2
        if-no-files-found: error

  make-release:
    runs-on: ubuntu-latest
    needs: [prepare, sources_collect, bookworm_build, archlinux_build, bitbake_build]
    steps:
      - name: Download bitbake artifacts
        uses: actions/download-artifact@v4
        with:
          name: bitbake-package
          path: ${{ env.PKGDEST }}
      - name: Download debian bookworm artifacts
        uses: actions/download-artifact@v4
        with:
          name: bookworm-package
          path: ${{ env.PKGDEST }}
      - name: Download archlinux artifacts
        uses: actions/download-artifact@v4
        with:
          name: archlinux-package
          path: ${{ env.PKGDEST }}
      - name: Download sources artifacts
        uses: actions/download-artifact@v4
        with:
          name: sources-package
          path: ${{ env.PKGDEST }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          name: login-ng v${{ env.RELEASE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            *.deb
            *.tar.bz2
            *.zip